# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/mcbuild/VstsAgent/work/158/b/cmake-3.19.2-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/mcbuild/VstsAgent/work/158/b/cmake-3.19.2-Linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mcbuild/VstsAgent/work/158/s

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/mcbuild/VstsAgent/work/158/b/cmake-3.19.2-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/mcbuild/VstsAgent/work/158/b/cmake-3.19.2-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/mcbuild/VstsAgent/work/158/b/cmake-3.19.2-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/mcbuild/VstsAgent/work/158/b/cmake-3.19.2-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/mcbuild/VstsAgent/work/158/b/cmake-3.19.2-Linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/mcbuild/VstsAgent/work/158/b/cmake-3.19.2-Linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/mcbuild/VstsAgent/work/158/b/cmake-3.19.2-Linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Devel\" \"Unspecified\" \"bedrock_replay\" \"libprotobuf\" \"libprotobuf-lite\" \"libprotoc\" \"linux_x64_public\" \"protobuf-export\" \"protobuf-headers\" \"protobuf-protos\" \"protoc\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && /home/mcbuild/VstsAgent/work/158/b/cmake-3.19.2-Linux-x86_64/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && /home/mcbuild/VstsAgent/work/158/b/cmake-3.19.2-Linux-x86_64/bin/cpack --config ./CPackSourceConfig.cmake /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/mcbuild/VstsAgent/work/158/b/cmake-3.19.2-Linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(CMAKE_COMMAND) -E cmake_progress_start /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public/CMakeFiles /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public/handheld/src-server//CMakeFiles/progress.marks
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 handheld/src-server/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 handheld/src-server/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 handheld/src-server/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 handheld/src-server/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
handheld/src-server/CMakeFiles/Minecraft.Server.dir/rule:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 handheld/src-server/CMakeFiles/Minecraft.Server.dir/rule
.PHONY : handheld/src-server/CMakeFiles/Minecraft.Server.dir/rule

# Convenience name for target.
Minecraft.Server: handheld/src-server/CMakeFiles/Minecraft.Server.dir/rule

.PHONY : Minecraft.Server

# fast build rule for target.
Minecraft.Server/fast:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/build
.PHONY : Minecraft.Server/fast

__/src-client/common/client/renderer/block/BlockGraphics.o: __/src-client/common/client/renderer/block/BlockGraphics.cpp.o

.PHONY : __/src-client/common/client/renderer/block/BlockGraphics.o

# target to build an object file
__/src-client/common/client/renderer/block/BlockGraphics.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/renderer/block/BlockGraphics.cpp.o
.PHONY : __/src-client/common/client/renderer/block/BlockGraphics.cpp.o

__/src-client/common/client/renderer/block/BlockGraphics.i: __/src-client/common/client/renderer/block/BlockGraphics.cpp.i

.PHONY : __/src-client/common/client/renderer/block/BlockGraphics.i

# target to preprocess a source file
__/src-client/common/client/renderer/block/BlockGraphics.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/renderer/block/BlockGraphics.cpp.i
.PHONY : __/src-client/common/client/renderer/block/BlockGraphics.cpp.i

__/src-client/common/client/renderer/block/BlockGraphics.s: __/src-client/common/client/renderer/block/BlockGraphics.cpp.s

.PHONY : __/src-client/common/client/renderer/block/BlockGraphics.s

# target to generate assembly for a file
__/src-client/common/client/renderer/block/BlockGraphics.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/renderer/block/BlockGraphics.cpp.s
.PHONY : __/src-client/common/client/renderer/block/BlockGraphics.cpp.s

__/src-client/common/client/renderer/texture/AtlasItemManager.o: __/src-client/common/client/renderer/texture/AtlasItemManager.cpp.o

.PHONY : __/src-client/common/client/renderer/texture/AtlasItemManager.o

# target to build an object file
__/src-client/common/client/renderer/texture/AtlasItemManager.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/renderer/texture/AtlasItemManager.cpp.o
.PHONY : __/src-client/common/client/renderer/texture/AtlasItemManager.cpp.o

__/src-client/common/client/renderer/texture/AtlasItemManager.i: __/src-client/common/client/renderer/texture/AtlasItemManager.cpp.i

.PHONY : __/src-client/common/client/renderer/texture/AtlasItemManager.i

# target to preprocess a source file
__/src-client/common/client/renderer/texture/AtlasItemManager.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/renderer/texture/AtlasItemManager.cpp.i
.PHONY : __/src-client/common/client/renderer/texture/AtlasItemManager.cpp.i

__/src-client/common/client/renderer/texture/AtlasItemManager.s: __/src-client/common/client/renderer/texture/AtlasItemManager.cpp.s

.PHONY : __/src-client/common/client/renderer/texture/AtlasItemManager.s

# target to generate assembly for a file
__/src-client/common/client/renderer/texture/AtlasItemManager.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/renderer/texture/AtlasItemManager.cpp.s
.PHONY : __/src-client/common/client/renderer/texture/AtlasItemManager.cpp.s

__/src-client/common/client/renderer/texture/IsotropicFaceData.o: __/src-client/common/client/renderer/texture/IsotropicFaceData.cpp.o

.PHONY : __/src-client/common/client/renderer/texture/IsotropicFaceData.o

# target to build an object file
__/src-client/common/client/renderer/texture/IsotropicFaceData.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/renderer/texture/IsotropicFaceData.cpp.o
.PHONY : __/src-client/common/client/renderer/texture/IsotropicFaceData.cpp.o

__/src-client/common/client/renderer/texture/IsotropicFaceData.i: __/src-client/common/client/renderer/texture/IsotropicFaceData.cpp.i

.PHONY : __/src-client/common/client/renderer/texture/IsotropicFaceData.i

# target to preprocess a source file
__/src-client/common/client/renderer/texture/IsotropicFaceData.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/renderer/texture/IsotropicFaceData.cpp.i
.PHONY : __/src-client/common/client/renderer/texture/IsotropicFaceData.cpp.i

__/src-client/common/client/renderer/texture/IsotropicFaceData.s: __/src-client/common/client/renderer/texture/IsotropicFaceData.cpp.s

.PHONY : __/src-client/common/client/renderer/texture/IsotropicFaceData.s

# target to generate assembly for a file
__/src-client/common/client/renderer/texture/IsotropicFaceData.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/renderer/texture/IsotropicFaceData.cpp.s
.PHONY : __/src-client/common/client/renderer/texture/IsotropicFaceData.cpp.s

__/src-client/common/client/renderer/texture/TextureUVCoordinateSet.o: __/src-client/common/client/renderer/texture/TextureUVCoordinateSet.cpp.o

.PHONY : __/src-client/common/client/renderer/texture/TextureUVCoordinateSet.o

# target to build an object file
__/src-client/common/client/renderer/texture/TextureUVCoordinateSet.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/renderer/texture/TextureUVCoordinateSet.cpp.o
.PHONY : __/src-client/common/client/renderer/texture/TextureUVCoordinateSet.cpp.o

__/src-client/common/client/renderer/texture/TextureUVCoordinateSet.i: __/src-client/common/client/renderer/texture/TextureUVCoordinateSet.cpp.i

.PHONY : __/src-client/common/client/renderer/texture/TextureUVCoordinateSet.i

# target to preprocess a source file
__/src-client/common/client/renderer/texture/TextureUVCoordinateSet.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/renderer/texture/TextureUVCoordinateSet.cpp.i
.PHONY : __/src-client/common/client/renderer/texture/TextureUVCoordinateSet.cpp.i

__/src-client/common/client/renderer/texture/TextureUVCoordinateSet.s: __/src-client/common/client/renderer/texture/TextureUVCoordinateSet.cpp.s

.PHONY : __/src-client/common/client/renderer/texture/TextureUVCoordinateSet.s

# target to generate assembly for a file
__/src-client/common/client/renderer/texture/TextureUVCoordinateSet.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/renderer/texture/TextureUVCoordinateSet.cpp.s
.PHONY : __/src-client/common/client/renderer/texture/TextureUVCoordinateSet.cpp.s

__/src-client/common/client/social/GameConnectionInfo.o: __/src-client/common/client/social/GameConnectionInfo.cpp.o

.PHONY : __/src-client/common/client/social/GameConnectionInfo.o

# target to build an object file
__/src-client/common/client/social/GameConnectionInfo.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/social/GameConnectionInfo.cpp.o
.PHONY : __/src-client/common/client/social/GameConnectionInfo.cpp.o

__/src-client/common/client/social/GameConnectionInfo.i: __/src-client/common/client/social/GameConnectionInfo.cpp.i

.PHONY : __/src-client/common/client/social/GameConnectionInfo.i

# target to preprocess a source file
__/src-client/common/client/social/GameConnectionInfo.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/social/GameConnectionInfo.cpp.i
.PHONY : __/src-client/common/client/social/GameConnectionInfo.cpp.i

__/src-client/common/client/social/GameConnectionInfo.s: __/src-client/common/client/social/GameConnectionInfo.cpp.s

.PHONY : __/src-client/common/client/social/GameConnectionInfo.s

# target to generate assembly for a file
__/src-client/common/client/social/GameConnectionInfo.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/__/src-client/common/client/social/GameConnectionInfo.cpp.s
.PHONY : __/src-client/common/client/social/GameConnectionInfo.cpp.s

common/ConsoleInputReader.o: common/ConsoleInputReader.cpp.o

.PHONY : common/ConsoleInputReader.o

# target to build an object file
common/ConsoleInputReader.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/ConsoleInputReader.cpp.o
.PHONY : common/ConsoleInputReader.cpp.o

common/ConsoleInputReader.i: common/ConsoleInputReader.cpp.i

.PHONY : common/ConsoleInputReader.i

# target to preprocess a source file
common/ConsoleInputReader.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/ConsoleInputReader.cpp.i
.PHONY : common/ConsoleInputReader.cpp.i

common/ConsoleInputReader.s: common/ConsoleInputReader.cpp.s

.PHONY : common/ConsoleInputReader.s

# target to generate assembly for a file
common/ConsoleInputReader.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/ConsoleInputReader.cpp.s
.PHONY : common/ConsoleInputReader.cpp.s

common/DedicatedServer.o: common/DedicatedServer.cpp.o

.PHONY : common/DedicatedServer.o

# target to build an object file
common/DedicatedServer.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/DedicatedServer.cpp.o
.PHONY : common/DedicatedServer.cpp.o

common/DedicatedServer.i: common/DedicatedServer.cpp.i

.PHONY : common/DedicatedServer.i

# target to preprocess a source file
common/DedicatedServer.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/DedicatedServer.cpp.i
.PHONY : common/DedicatedServer.cpp.i

common/DedicatedServer.s: common/DedicatedServer.cpp.s

.PHONY : common/DedicatedServer.s

# target to generate assembly for a file
common/DedicatedServer.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/DedicatedServer.cpp.s
.PHONY : common/DedicatedServer.cpp.s

common/DedicatedServerCommands.o: common/DedicatedServerCommands.cpp.o

.PHONY : common/DedicatedServerCommands.o

# target to build an object file
common/DedicatedServerCommands.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/DedicatedServerCommands.cpp.o
.PHONY : common/DedicatedServerCommands.cpp.o

common/DedicatedServerCommands.i: common/DedicatedServerCommands.cpp.i

.PHONY : common/DedicatedServerCommands.i

# target to preprocess a source file
common/DedicatedServerCommands.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/DedicatedServerCommands.cpp.i
.PHONY : common/DedicatedServerCommands.cpp.i

common/DedicatedServerCommands.s: common/DedicatedServerCommands.cpp.s

.PHONY : common/DedicatedServerCommands.s

# target to generate assembly for a file
common/DedicatedServerCommands.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/DedicatedServerCommands.cpp.s
.PHONY : common/DedicatedServerCommands.cpp.s

common/DedicatedServerGameTestRunner.o: common/DedicatedServerGameTestRunner.cpp.o

.PHONY : common/DedicatedServerGameTestRunner.o

# target to build an object file
common/DedicatedServerGameTestRunner.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/DedicatedServerGameTestRunner.cpp.o
.PHONY : common/DedicatedServerGameTestRunner.cpp.o

common/DedicatedServerGameTestRunner.i: common/DedicatedServerGameTestRunner.cpp.i

.PHONY : common/DedicatedServerGameTestRunner.i

# target to preprocess a source file
common/DedicatedServerGameTestRunner.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/DedicatedServerGameTestRunner.cpp.i
.PHONY : common/DedicatedServerGameTestRunner.cpp.i

common/DedicatedServerGameTestRunner.s: common/DedicatedServerGameTestRunner.cpp.s

.PHONY : common/DedicatedServerGameTestRunner.s

# target to generate assembly for a file
common/DedicatedServerGameTestRunner.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/DedicatedServerGameTestRunner.cpp.s
.PHONY : common/DedicatedServerGameTestRunner.cpp.s

common/PropertiesSettings.o: common/PropertiesSettings.cpp.o

.PHONY : common/PropertiesSettings.o

# target to build an object file
common/PropertiesSettings.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/PropertiesSettings.cpp.o
.PHONY : common/PropertiesSettings.cpp.o

common/PropertiesSettings.i: common/PropertiesSettings.cpp.i

.PHONY : common/PropertiesSettings.i

# target to preprocess a source file
common/PropertiesSettings.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/PropertiesSettings.cpp.i
.PHONY : common/PropertiesSettings.cpp.i

common/PropertiesSettings.s: common/PropertiesSettings.cpp.s

.PHONY : common/PropertiesSettings.s

# target to generate assembly for a file
common/PropertiesSettings.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/PropertiesSettings.cpp.s
.PHONY : common/PropertiesSettings.cpp.s

common/TestConfig.o: common/TestConfig.cpp.o

.PHONY : common/TestConfig.o

# target to build an object file
common/TestConfig.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/TestConfig.cpp.o
.PHONY : common/TestConfig.cpp.o

common/TestConfig.i: common/TestConfig.cpp.i

.PHONY : common/TestConfig.i

# target to preprocess a source file
common/TestConfig.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/TestConfig.cpp.i
.PHONY : common/TestConfig.cpp.i

common/TestConfig.s: common/TestConfig.cpp.s

.PHONY : common/TestConfig.s

# target to generate assembly for a file
common/TestConfig.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/TestConfig.cpp.s
.PHONY : common/TestConfig.cpp.s

common/TestDedicatedServerCommands.o: common/TestDedicatedServerCommands.cpp.o

.PHONY : common/TestDedicatedServerCommands.o

# target to build an object file
common/TestDedicatedServerCommands.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/TestDedicatedServerCommands.cpp.o
.PHONY : common/TestDedicatedServerCommands.cpp.o

common/TestDedicatedServerCommands.i: common/TestDedicatedServerCommands.cpp.i

.PHONY : common/TestDedicatedServerCommands.i

# target to preprocess a source file
common/TestDedicatedServerCommands.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/TestDedicatedServerCommands.cpp.i
.PHONY : common/TestDedicatedServerCommands.cpp.i

common/TestDedicatedServerCommands.s: common/TestDedicatedServerCommands.cpp.s

.PHONY : common/TestDedicatedServerCommands.s

# target to generate assembly for a file
common/TestDedicatedServerCommands.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/TestDedicatedServerCommands.cpp.s
.PHONY : common/TestDedicatedServerCommands.cpp.s

common/VanillaGameModuleDedicatedServer.o: common/VanillaGameModuleDedicatedServer.cpp.o

.PHONY : common/VanillaGameModuleDedicatedServer.o

# target to build an object file
common/VanillaGameModuleDedicatedServer.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/VanillaGameModuleDedicatedServer.cpp.o
.PHONY : common/VanillaGameModuleDedicatedServer.cpp.o

common/VanillaGameModuleDedicatedServer.i: common/VanillaGameModuleDedicatedServer.cpp.i

.PHONY : common/VanillaGameModuleDedicatedServer.i

# target to preprocess a source file
common/VanillaGameModuleDedicatedServer.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/VanillaGameModuleDedicatedServer.cpp.i
.PHONY : common/VanillaGameModuleDedicatedServer.cpp.i

common/VanillaGameModuleDedicatedServer.s: common/VanillaGameModuleDedicatedServer.cpp.s

.PHONY : common/VanillaGameModuleDedicatedServer.s

# target to generate assembly for a file
common/VanillaGameModuleDedicatedServer.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/VanillaGameModuleDedicatedServer.cpp.s
.PHONY : common/VanillaGameModuleDedicatedServer.cpp.s

common/commands/ChangeSettingCommand.o: common/commands/ChangeSettingCommand.cpp.o

.PHONY : common/commands/ChangeSettingCommand.o

# target to build an object file
common/commands/ChangeSettingCommand.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/ChangeSettingCommand.cpp.o
.PHONY : common/commands/ChangeSettingCommand.cpp.o

common/commands/ChangeSettingCommand.i: common/commands/ChangeSettingCommand.cpp.i

.PHONY : common/commands/ChangeSettingCommand.i

# target to preprocess a source file
common/commands/ChangeSettingCommand.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/ChangeSettingCommand.cpp.i
.PHONY : common/commands/ChangeSettingCommand.cpp.i

common/commands/ChangeSettingCommand.s: common/commands/ChangeSettingCommand.cpp.s

.PHONY : common/commands/ChangeSettingCommand.s

# target to generate assembly for a file
common/commands/ChangeSettingCommand.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/ChangeSettingCommand.cpp.s
.PHONY : common/commands/ChangeSettingCommand.cpp.s

common/commands/DedicatedWSServerCommand.o: common/commands/DedicatedWSServerCommand.cpp.o

.PHONY : common/commands/DedicatedWSServerCommand.o

# target to build an object file
common/commands/DedicatedWSServerCommand.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/DedicatedWSServerCommand.cpp.o
.PHONY : common/commands/DedicatedWSServerCommand.cpp.o

common/commands/DedicatedWSServerCommand.i: common/commands/DedicatedWSServerCommand.cpp.i

.PHONY : common/commands/DedicatedWSServerCommand.i

# target to preprocess a source file
common/commands/DedicatedWSServerCommand.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/DedicatedWSServerCommand.cpp.i
.PHONY : common/commands/DedicatedWSServerCommand.cpp.i

common/commands/DedicatedWSServerCommand.s: common/commands/DedicatedWSServerCommand.cpp.s

.PHONY : common/commands/DedicatedWSServerCommand.s

# target to generate assembly for a file
common/commands/DedicatedWSServerCommand.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/DedicatedWSServerCommand.cpp.s
.PHONY : common/commands/DedicatedWSServerCommand.cpp.s

common/commands/GetEduServerInfoCommand.o: common/commands/GetEduServerInfoCommand.cpp.o

.PHONY : common/commands/GetEduServerInfoCommand.o

# target to build an object file
common/commands/GetEduServerInfoCommand.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/GetEduServerInfoCommand.cpp.o
.PHONY : common/commands/GetEduServerInfoCommand.cpp.o

common/commands/GetEduServerInfoCommand.i: common/commands/GetEduServerInfoCommand.cpp.i

.PHONY : common/commands/GetEduServerInfoCommand.i

# target to preprocess a source file
common/commands/GetEduServerInfoCommand.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/GetEduServerInfoCommand.cpp.i
.PHONY : common/commands/GetEduServerInfoCommand.cpp.i

common/commands/GetEduServerInfoCommand.s: common/commands/GetEduServerInfoCommand.cpp.s

.PHONY : common/commands/GetEduServerInfoCommand.s

# target to generate assembly for a file
common/commands/GetEduServerInfoCommand.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/GetEduServerInfoCommand.cpp.s
.PHONY : common/commands/GetEduServerInfoCommand.cpp.s

common/commands/SaveCommand.o: common/commands/SaveCommand.cpp.o

.PHONY : common/commands/SaveCommand.o

# target to build an object file
common/commands/SaveCommand.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/SaveCommand.cpp.o
.PHONY : common/commands/SaveCommand.cpp.o

common/commands/SaveCommand.i: common/commands/SaveCommand.cpp.i

.PHONY : common/commands/SaveCommand.i

# target to preprocess a source file
common/commands/SaveCommand.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/SaveCommand.cpp.i
.PHONY : common/commands/SaveCommand.cpp.i

common/commands/SaveCommand.s: common/commands/SaveCommand.cpp.s

.PHONY : common/commands/SaveCommand.s

# target to generate assembly for a file
common/commands/SaveCommand.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/SaveCommand.cpp.s
.PHONY : common/commands/SaveCommand.cpp.s

common/commands/ServerLogCommand.o: common/commands/ServerLogCommand.cpp.o

.PHONY : common/commands/ServerLogCommand.o

# target to build an object file
common/commands/ServerLogCommand.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/ServerLogCommand.cpp.o
.PHONY : common/commands/ServerLogCommand.cpp.o

common/commands/ServerLogCommand.i: common/commands/ServerLogCommand.cpp.i

.PHONY : common/commands/ServerLogCommand.i

# target to preprocess a source file
common/commands/ServerLogCommand.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/ServerLogCommand.cpp.i
.PHONY : common/commands/ServerLogCommand.cpp.i

common/commands/ServerLogCommand.s: common/commands/ServerLogCommand.cpp.s

.PHONY : common/commands/ServerLogCommand.s

# target to generate assembly for a file
common/commands/ServerLogCommand.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/ServerLogCommand.cpp.s
.PHONY : common/commands/ServerLogCommand.cpp.s

common/commands/StopCommand.o: common/commands/StopCommand.cpp.o

.PHONY : common/commands/StopCommand.o

# target to build an object file
common/commands/StopCommand.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/StopCommand.cpp.o
.PHONY : common/commands/StopCommand.cpp.o

common/commands/StopCommand.i: common/commands/StopCommand.cpp.i

.PHONY : common/commands/StopCommand.i

# target to preprocess a source file
common/commands/StopCommand.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/StopCommand.cpp.i
.PHONY : common/commands/StopCommand.cpp.i

common/commands/StopCommand.s: common/commands/StopCommand.cpp.s

.PHONY : common/commands/StopCommand.s

# target to generate assembly for a file
common/commands/StopCommand.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/StopCommand.cpp.s
.PHONY : common/commands/StopCommand.cpp.s

common/commands/WhitelistCommand.o: common/commands/WhitelistCommand.cpp.o

.PHONY : common/commands/WhitelistCommand.o

# target to build an object file
common/commands/WhitelistCommand.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/WhitelistCommand.cpp.o
.PHONY : common/commands/WhitelistCommand.cpp.o

common/commands/WhitelistCommand.i: common/commands/WhitelistCommand.cpp.i

.PHONY : common/commands/WhitelistCommand.i

# target to preprocess a source file
common/commands/WhitelistCommand.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/WhitelistCommand.cpp.i
.PHONY : common/commands/WhitelistCommand.cpp.i

common/commands/WhitelistCommand.s: common/commands/WhitelistCommand.cpp.s

.PHONY : common/commands/WhitelistCommand.s

# target to generate assembly for a file
common/commands/WhitelistCommand.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/common/commands/WhitelistCommand.cpp.s
.PHONY : common/commands/WhitelistCommand.cpp.s

linux/ServerMetricsImpl.o: linux/ServerMetricsImpl.cpp.o

.PHONY : linux/ServerMetricsImpl.o

# target to build an object file
linux/ServerMetricsImpl.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/linux/ServerMetricsImpl.cpp.o
.PHONY : linux/ServerMetricsImpl.cpp.o

linux/ServerMetricsImpl.i: linux/ServerMetricsImpl.cpp.i

.PHONY : linux/ServerMetricsImpl.i

# target to preprocess a source file
linux/ServerMetricsImpl.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/linux/ServerMetricsImpl.cpp.i
.PHONY : linux/ServerMetricsImpl.cpp.i

linux/ServerMetricsImpl.s: linux/ServerMetricsImpl.cpp.s

.PHONY : linux/ServerMetricsImpl.s

# target to generate assembly for a file
linux/ServerMetricsImpl.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/linux/ServerMetricsImpl.cpp.s
.PHONY : linux/ServerMetricsImpl.cpp.s

linux/clacks-server/ClacksServer.o: linux/clacks-server/ClacksServer.cpp.o

.PHONY : linux/clacks-server/ClacksServer.o

# target to build an object file
linux/clacks-server/ClacksServer.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/linux/clacks-server/ClacksServer.cpp.o
.PHONY : linux/clacks-server/ClacksServer.cpp.o

linux/clacks-server/ClacksServer.i: linux/clacks-server/ClacksServer.cpp.i

.PHONY : linux/clacks-server/ClacksServer.i

# target to preprocess a source file
linux/clacks-server/ClacksServer.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/linux/clacks-server/ClacksServer.cpp.i
.PHONY : linux/clacks-server/ClacksServer.cpp.i

linux/clacks-server/ClacksServer.s: linux/clacks-server/ClacksServer.cpp.s

.PHONY : linux/clacks-server/ClacksServer.s

# target to generate assembly for a file
linux/clacks-server/ClacksServer.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/linux/clacks-server/ClacksServer.cpp.s
.PHONY : linux/clacks-server/ClacksServer.cpp.s

linux/main_dedicated.o: linux/main_dedicated.cpp.o

.PHONY : linux/main_dedicated.o

# target to build an object file
linux/main_dedicated.cpp.o:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/linux/main_dedicated.cpp.o
.PHONY : linux/main_dedicated.cpp.o

linux/main_dedicated.i: linux/main_dedicated.cpp.i

.PHONY : linux/main_dedicated.i

# target to preprocess a source file
linux/main_dedicated.cpp.i:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/linux/main_dedicated.cpp.i
.PHONY : linux/main_dedicated.cpp.i

linux/main_dedicated.s: linux/main_dedicated.cpp.s

.PHONY : linux/main_dedicated.s

# target to generate assembly for a file
linux/main_dedicated.cpp.s:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(MAKE) $(MAKESILENT) -f handheld/src-server/CMakeFiles/Minecraft.Server.dir/build.make handheld/src-server/CMakeFiles/Minecraft.Server.dir/linux/main_dedicated.cpp.s
.PHONY : linux/main_dedicated.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... Minecraft.Server"
	@echo "... __/src-client/common/client/renderer/block/BlockGraphics.o"
	@echo "... __/src-client/common/client/renderer/block/BlockGraphics.i"
	@echo "... __/src-client/common/client/renderer/block/BlockGraphics.s"
	@echo "... __/src-client/common/client/renderer/texture/AtlasItemManager.o"
	@echo "... __/src-client/common/client/renderer/texture/AtlasItemManager.i"
	@echo "... __/src-client/common/client/renderer/texture/AtlasItemManager.s"
	@echo "... __/src-client/common/client/renderer/texture/IsotropicFaceData.o"
	@echo "... __/src-client/common/client/renderer/texture/IsotropicFaceData.i"
	@echo "... __/src-client/common/client/renderer/texture/IsotropicFaceData.s"
	@echo "... __/src-client/common/client/renderer/texture/TextureUVCoordinateSet.o"
	@echo "... __/src-client/common/client/renderer/texture/TextureUVCoordinateSet.i"
	@echo "... __/src-client/common/client/renderer/texture/TextureUVCoordinateSet.s"
	@echo "... __/src-client/common/client/social/GameConnectionInfo.o"
	@echo "... __/src-client/common/client/social/GameConnectionInfo.i"
	@echo "... __/src-client/common/client/social/GameConnectionInfo.s"
	@echo "... common/ConsoleInputReader.o"
	@echo "... common/ConsoleInputReader.i"
	@echo "... common/ConsoleInputReader.s"
	@echo "... common/DedicatedServer.o"
	@echo "... common/DedicatedServer.i"
	@echo "... common/DedicatedServer.s"
	@echo "... common/DedicatedServerCommands.o"
	@echo "... common/DedicatedServerCommands.i"
	@echo "... common/DedicatedServerCommands.s"
	@echo "... common/DedicatedServerGameTestRunner.o"
	@echo "... common/DedicatedServerGameTestRunner.i"
	@echo "... common/DedicatedServerGameTestRunner.s"
	@echo "... common/PropertiesSettings.o"
	@echo "... common/PropertiesSettings.i"
	@echo "... common/PropertiesSettings.s"
	@echo "... common/TestConfig.o"
	@echo "... common/TestConfig.i"
	@echo "... common/TestConfig.s"
	@echo "... common/TestDedicatedServerCommands.o"
	@echo "... common/TestDedicatedServerCommands.i"
	@echo "... common/TestDedicatedServerCommands.s"
	@echo "... common/VanillaGameModuleDedicatedServer.o"
	@echo "... common/VanillaGameModuleDedicatedServer.i"
	@echo "... common/VanillaGameModuleDedicatedServer.s"
	@echo "... common/commands/ChangeSettingCommand.o"
	@echo "... common/commands/ChangeSettingCommand.i"
	@echo "... common/commands/ChangeSettingCommand.s"
	@echo "... common/commands/DedicatedWSServerCommand.o"
	@echo "... common/commands/DedicatedWSServerCommand.i"
	@echo "... common/commands/DedicatedWSServerCommand.s"
	@echo "... common/commands/GetEduServerInfoCommand.o"
	@echo "... common/commands/GetEduServerInfoCommand.i"
	@echo "... common/commands/GetEduServerInfoCommand.s"
	@echo "... common/commands/SaveCommand.o"
	@echo "... common/commands/SaveCommand.i"
	@echo "... common/commands/SaveCommand.s"
	@echo "... common/commands/ServerLogCommand.o"
	@echo "... common/commands/ServerLogCommand.i"
	@echo "... common/commands/ServerLogCommand.s"
	@echo "... common/commands/StopCommand.o"
	@echo "... common/commands/StopCommand.i"
	@echo "... common/commands/StopCommand.s"
	@echo "... common/commands/WhitelistCommand.o"
	@echo "... common/commands/WhitelistCommand.i"
	@echo "... common/commands/WhitelistCommand.s"
	@echo "... linux/ServerMetricsImpl.o"
	@echo "... linux/ServerMetricsImpl.i"
	@echo "... linux/ServerMetricsImpl.s"
	@echo "... linux/clacks-server/ClacksServer.o"
	@echo "... linux/clacks-server/ClacksServer.i"
	@echo "... linux/clacks-server/ClacksServer.s"
	@echo "... linux/main_dedicated.o"
	@echo "... linux/main_dedicated.i"
	@echo "... linux/main_dedicated.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/mcbuild/VstsAgent/work/158/s/build_linux_x64_public && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

